### ISSUE TITLE
Issues when communicating with inverter

### ISSUE THREAD

**Issue by marval** [klatremis/esphome-for-deye#33]
Hello,

New to Deye, but generally not new to electronics or ESP programming. I have recently purchased a 12kW hybrid inverter and it should obviously integrates to HA so this code was on my favorites even before the purchase.

After getting the inverter I soldered my 485 to TTL module on an ESP32 I had laying around and connected it using the diagrams in the manual (pin 1 and pin 2 on RJ45) and put it in the Modbus port on the inverter. The ESP kept sending but never received anything (LED lights) so even though I was sure about the connections I exchanged the TX and RX - still not working. I then returned the RX and TX wires to their original placement and started plugging the RJ45 in the other ports. Only the Meter485 port worked for me, but even this was not 100%. I could read all the values, but whenever I wrote something it got overwritten with the old value after a few seconds. 

Am I doing something wrong or missing a small detail somewhere?

Here is a picture of my FW version.
![434243128_980765883491979_7588102023907401539_n](https://github.com/klatremis/esphome-for-deye/assets/1443599/713a71d9-392a-4a55-8734-72a0678daddd)

**Comment by luckylinux** [comment]
Did you connect the GND Port / Wire as well (Pin 3 if you used Pin 1 + 2 for TX/RX) ?

https://private-user-images.githubusercontent.com/7126291/318758677-615df540-39a8-4c8b-96da-6476480698f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjEzNDUsIm5iZiI6MTcxMjIyMTA0NSwicGF0aCI6Ii83MTI2MjkxLzMxODc1ODY3Ny02MTVkZjU0MC0zOWE4LTRjOGItOTZkYS02NDc2NDgwNjk4ZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDg1NzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjAzNjQzOWVjYzdjMjUwZTg4NWJiMmNhNWE0ZjUwOGE2YWM4MWJkNjY0YjZmZGZlMjJmMDE5NTUwNGM3NzZjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i-E2eriaQEhUhZvgvtsXH96flqErTUxRkAkE-sQZ0wA

Are you sure you don't have a 3.3V/5V issue for instance, both for NOT damaging the Deye, as well as the Operating Voltage of your Transceiver ? E.g. MAX485 is NOT meant to operate at 3.3 V, you should use MAX3485 for that in theory (although MAX485 could work and sometimes does).

Other options is the Pinout on the ESP32 side (GPIO mappings)

I tried to do my own fork at https://github.com/luckylinux/esphome-for-deye with a more modular approach (using ESPHome Packages) and since I work off-grid I had a lot more registers to consider.

I will be testing in a few days when I get the 10m RJ45 Cables that I ordered. I was too lazy to crimp them myself :D. I will be using a M5Stack Atom S3 Lite with Galvanically Isolated RS485 to have some extra safety.

**Comment by luckylinux** [comment]
@marval

For what it's worth, I could successfully upload my forked version (on the Modbus port) and it worked out of the box on the Atom S3 Lite with the Isolated RS485 Module/Unit. 

Pinout was correct from the start and communication was immediately established.

The minor fix I needed was to change device_type so it had a unique ID since I have 3 inverters otherwise that would generate conflicts in MQTT / Home Assistant (obviously).

But all of it is now included in my latest version.

https://github.com/luckylinux/esphome-for-deye

**Comment by marval** [comment]
Just an update from my side. It seems the issue was neither HW or FW specific. I did two things and my problems are now gone
1. @luckylinux got me thinking about the ID so I checked and it was 01. Decided to change it to 05 and then back to 01 while keeping rhe inverter as a “Slave” (how come they only updated the branch names and not these uses of the words 🤔)
![image](https://github.com/klatremis/esphome-for-deye/assets/1443599/2c8599c6-cc76-4617-9727-f5582c807d25)
2. Changed to pin 7 and 8 (the brown pair). This then worked in the Modbus port which was otherwise dead. 

Now everything works and I am happy with how it turned out. Thanks @klatremis for his effort on setting up things so that they are easy for (the most of 😬) us.

**Comment by luckylinux** [comment]
@marval I'm glad that you got it solved, however for the first change you did I'm not sure why that should have any influence.

That's the ID for master/slave setup when using parallel inverters setup.

I do not see how that should relate to the Modbus port
![image](https://github.com/klatremis/esphome-for-deye/assets/7126291/3759d473-6ccc-48ac-834c-3a21b15d9228)

More likely than not, in my opinion, you counted in the "wrong" way the pins (look at RJ45 plug with locking tab up/down, from the front/back, etc) on the RJ45 plug and/or other end of the cable AND you used TIA 568A wiring.

In your original cabling, were you maybe using the Green / White-Green Wires as in TIA 568B ? That would explain why they are going nowhere if you did TIA 568A on the other end:
![image](https://github.com/klatremis/esphome-for-deye/assets/7126291/8ae0e73e-4f37-473a-b957-f1298b82c98f)

The end result is that you had a cross-over cable.

Because for TIA 568B, if the Deye schematics is correct, then it should also have worked from the start, since the pins are bridged internally to the device:
![image](https://github.com/klatremis/esphome-for-deye/assets/7126291/64453ba6-ac75-47de-9a29-6520ba065c52)

![image](https://github.com/klatremis/esphome-for-deye/assets/7126291/723cbdd3-a47d-4b69-9645-b67bebd6281d)

Pin 1 is bridged with Pin 8 (RS485_B) and Pin 2 is bridged with Pin 7 (RS485_A).

Impossible to know since you did not provide any pictures of the RJ45 plug or the ESP32 RS485 Transceiver end, nor any details on the cable wiring type (TIA 568A or TIA 568B) ...

**Comment by marval** [comment]
I was using TIA 568B and I am pretty confident in the counting and identifying pins. As stated before - I could see both the TX and RX on the transceiver blink so I assume the communication was established.

No idea how the parallel setup has affected this. If I find some spare time I will try to reverse the changes one by one to see what made the difference.

**Comment by luckylinux** [comment]
Alright, thanks for the quicky reply. I'm interested to see what was really causing this.
